// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntflzhowlkdimyhcihwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50Zmx6aG93bGtkaW15aGNpaHdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NjU4NTgsImV4cCI6MjA3MDU0MTg1OH0.bXe8OVVdVAqAfGgmEv7fToW2KV8SqwFwta30Nd6l6Z0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});